name: SimpleUtils
author: Mooy1
description: Simple utility items for slimefun
website: https://github.com/ybw0014/SimpleUtils
main: io.github.mooy1.simpleutils.SimpleUtils
depend: [Slimefun]
softdepend: [InfinityExpansion, GuizhanLibPlugin]
version: ${project.version}
api-version: 1.16
folia-supported: true

commands:
  simpleutils:
    description: Do /simpleutils help for a list of commands
    usage: /simpleutils <subcommand>
    aliases: [ su, simple ]
